# Practical 20

# For teleco churn dataset train a model using KNN Classifier and select K Neighbors to find out optimal value of K. Also find accuracy score for each chosen neighbor

In [1]:
import numpy as np  #importing the libraries
import pandas as pd
from matplotlib import pyplot
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [2]:
df = pd.read_csv(r"D:\Machine Learning\Telecustomers.csv")  #importing the dataset

In [3]:
df

region  tenure  age  marital  address  income  ed  employ  retire  \
0         2      13   44        1        9    64.0   4       5     0.0   
1         3      11   33        1        7   136.0   5       5     0.0   
2         3      68   52        1       24   116.0   1      29     0.0   
3         2      33   33        0       12    33.0   2       0     0.0   
4         2      23   30        1        9    30.0   1       2     0.0   
..      ...     ...  ...      ...      ...     ...  ..     ...     ...   
995       3      10   39        0        0    27.0   3       0     0.0   
996       1       7   34        0        2    22.0   5       5     0.0   
997       3      67   59        0       40   944.0   5      33     0.0   
998       3      70   49        0       18    87.0   2      22     0.0   
999       3      50   36        1        7    39.0   3       3     0.0   

     gender  reside  custcat  
0         0       2        1  
1         0       6        4  
2         1       2        3  
3         1       1        1  
4         0       4        3  
..      ...     ...      ...  
995       1       3        1  
996       1       1        1  
997       1       1        4  
998       1       1        3  
999       1       3        2  

[1000 rows x 12 columns]

In [4]:
#region,tenure,age,marital,address,income,ed,employ,retire,gender,reside,custcat
    #custcat
        #1 basic service
        #2 e service
        #3 plus service
        #4 total service

In [26]:
df.describe()  # getting the basic statistical values of the dataset

region       tenure          age      marital      address  \
count  1000.0000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      2.0220    35.526000    41.684000     0.495000    11.551000   
std       0.8162    21.359812    12.558816     0.500225    10.086681   
min       1.0000     1.000000    18.000000     0.000000     0.000000   
25%       1.0000    17.000000    32.000000     0.000000     3.000000   
50%       2.0000    34.000000    40.000000     0.000000     9.000000   
75%       3.0000    54.000000    51.000000     1.000000    18.000000   
max       3.0000    72.000000    77.000000     1.000000    55.000000   

            income           ed       employ       retire       gender  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean     77.535000     2.671000    10.987000     0.047000     0.517000   
std     107.044165     1.222397    10.082087     0.211745     0.499961   
min       9.000000     1.000000     0.000000     0.000000     0.000000   
25%      29.000000     2.000000     3.000000     0.000000     0.000000   
50%      47.000000     3.000000     8.000000     0.000000     1.000000   
75%      83.000000     4.000000    17.000000     0.000000     1.000000   
max    1668.000000     5.000000    47.000000     1.000000     1.000000   

            reside      custcat  
count  1000.000000  1000.000000  
mean      2.331000     2.487000  
std       1.435793     1.120306  
min       1.000000     1.000000  
25%       1.000000     1.000000  
50%       2.000000     3.000000  
75%       3.000000     3.000000  
max       8.000000     4.000000

In [6]:
df["custcat"].value_counts()  # counting the number of occurences of each category

3    281
1    266
4    236
2    217
Name: custcat, dtype: int64

In [7]:
df.columns  #columns heading

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [8]:
#seperating dependent and independent variables
x = df[['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed', 'employ', 'retire', 'gender', 'reside']].values
print(x[0:5])
y = df['custcat'].values
print(y[0:5])

[[  2.  13.  44.   1.   9.  64.   4.   5.   0.   0.   2.]
 [  3.  11.  33.   1.   7. 136.   5.   5.   0.   0.   6.]
 [  3.  68.  52.   1.  24. 116.   1.  29.   0.   1.   2.]
 [  2.  33.  33.   0.  12.  33.   2.   0.   0.   1.   1.]
 [  2.  23.  30.   1.   9.  30.   1.   2.   0.   0.   4.]]
[1 4 3 1 3]


In [9]:
x = preprocessing.StandardScaler().fit(x).transform(x.astype(float))  #scaling, fitting and transforming
# in this step we are using anonymous objects. linking objects without makig them refer is called anonymous objects
x[0:10]

array([[-0.02696767, -1.055125  ,  0.18450456,  1.0100505 , -0.25303431,
        -0.12650641,  1.0877526 , -0.5941226 , -0.22207644, -1.03459817,
        -0.23065004],
       [ 1.19883553, -1.14880563, -0.69181243,  1.0100505 , -0.4514148 ,
         0.54644972,  1.9062271 , -0.5941226 , -0.22207644, -1.03459817,
         2.55666158],
       [ 1.19883553,  1.52109247,  0.82182601,  1.0100505 ,  1.23481934,
         0.35951747, -1.36767088,  1.78752803, -0.22207644,  0.96655883,
        -0.23065004],
       [-0.02696767, -0.11831864, -0.69181243, -0.9900495 ,  0.04453642,
        -0.41625141, -0.54919639, -1.09029981, -0.22207644,  0.96655883,
        -0.92747794],
       [-0.02696767, -0.58672182, -0.93080797,  1.0100505 , -0.25303431,
        -0.44429125, -1.36767088, -0.89182893, -0.22207644, -1.03459817,
         1.16300577],
       [-0.02696767,  0.2564039 , -0.21382135, -0.9900495 ,  0.54048764,
         0.00434618, -0.54919639,  0.49746728, -0.22207644,  0.96655883,
        -0.927

In [10]:
from sklearn.model_selection import train_test_split  # Splitting the data into training and test set
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.neighbors import KNeighborsClassifier  # importing the KNN Classifier
from sklearn import metrics
k = 4
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)

In [12]:
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 4 is :", metrics.accuracy_score(ytest, predy))

Accuracy of model at K = 4 is : 0.295


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [13]:
k = 5  #checking the accuracy of model at K = 5
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 5 is :", metrics.accuracy_score(ytest, predy))

Accuracy of model at K = 5 is : 0.32


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [14]:
k = 6  #checking the accuracy of model at K = 6
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 6 is :", metrics.accuracy_score(ytest, predy))

Accuracy of model at K = 6 is : 0.31


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [15]:
k = 7  #checking the accuracy of model at K = 7
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 7 is :", metrics.accuracy_score(ytest, predy))

Accuracy of model at K = 7 is : 0.34


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [16]:
k = 8  #checking the accuracy of model at K = 8
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 8 is :", metrics.accuracy_score(ytest, predy))

Accuracy of model at K = 8 is : 0.34


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [17]:
k = 16  #checking the accuracy of model at K = 16
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 16 is :", metrics.accuracy_score(ytest, predy))

Accuracy of model at K = 16 is : 0.325


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [22]:
k = 46  #checking the accuracy of model at K = 46
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(xtrain, ytrain)
predy = knnClassifier.predict(xtest)
print("Accuracy of model at K = 46 is :", metrics.accuracy_score(ytest, predy))
confusion_matrix = metrics.confusion_matrix(ytest, predy)
print(confusion_matrix)

Accuracy of model at K = 46 is : 0.37
[[34  1 22  4]
 [10  8 14 12]
 [14 15 17  4]
 [12  9  9 15]]


C:\Users\ANIKET KUMAR\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [23]:
print(metrics.classification_report(ytest, predy))

              precision    recall  f1-score   support

           1       0.49      0.56      0.52        61
           2       0.24      0.18      0.21        44
           3       0.27      0.34      0.30        50
           4       0.43      0.33      0.38        45

    accuracy                           0.37       200
   macro avg       0.36      0.35      0.35       200
weighted avg       0.37      0.37      0.36       200

